---
title: "ML2 Final Project - Time Series Model"
author: "Brady Hobson, Sara Kent"
date: "2025-04-14"
output:
  html_document: default
  pdf_document: default
---


```{r}
# read in the lmp data
lmp_df <- read.csv("lmp_data.csv", row.names = 1)
head(lmp_df)
```

```{r}
# keep only the interval local time and the lmp
lmp_df <- lmp_df[, c("interval_end_local", "lmp")]
head(lmp_df)
```

```{r}
series <- ts(lmp_df$lmp)

# acf and pacf plots
acf(series, main="Bearswamp LMP ACF plot")
pacf(series, main="Bearswamp LMP PACF plot")
```

```{r}
#split into train and test sets
train_size <- floor(0.8 * nrow(lmp_df))
train_data <- lmp_df[1:train_size, ]
test_data <- lmp_df[(train_size +1 ):nrow(lmp_df),]

y_train <- train_data$lmp
y_test <- test_data$lmp

# number of lags to include in the model
lags <- 12

# create x and y matrices
# docs for embed: http://rdocumentation.org/packages/stats/versions/3.6.2/topics/embed
X <- embed(y_train, lags + 1)
y <- X[, lags + 1] 

# remove last column from X because it's current value
X <- X[, -ncol(X)]

# add intercept
X <- cbind(1, X)

# fit using OLS
XTX <- t(X) %*% X 
XTX_inv <- solve(XTX)
XTy <- t(X) %*% y
weights <- XTX_inv %*% XTy 

# print coefficeints
cat("AR model coefficients:\n")
print(weights)
```

```{r}
# predict on test set
test_predictions <- numeric(length(y_test))

for (i in 1:length(y_test)) {
  if (i <= 12) {
    # use lag from training set for the first predictions
    lags <- tail(y_train, 12)[(12 - i + 1):12]
  } else {
    # otherwise use last predicted
    lags <- test_predictions[(i - 12):(i - 1)]
  }
  # add bias term
  lags_with_bias <- c(1, lags)
  
  # apply coefficients to lags
  weighted_lags <- lags_with_bias * weights
  
  # calculate prediction
  test_predictions[i] <- sum(weighted_lags)
}

```

```{r}
# plot the actuals vs predicted
plot(y_test, type = "l", col = "blue", lwd = 2, ylab = "LMP", xlab = "Time", 
     main = "Test Predictions vs Actual")
lines(test_predictions, col = "red", lwd = 2) 
legend("topright", legend = c("Actual", "Predicted"), col = c("blue", "red"), lty = 1, lwd = 2)

```

```{r}
# plot the first 15 values
y_test_subset <- y_test[1:15]
test_predictions_subset <- test_predictions[1:15]
plot(y_test_subset, type = "l", col = "blue", lwd = 2, ylab = "LMP", xlab = "Time", 
     main = "First 15 Test Predictions vs Actual", ylim = c(-10, max(c(y_test_subset, test_predictions_subset))))
lines(test_predictions_subset, col = "red", lwd = 2)
legend("topright", legend = c("Actual", "Predicted"), col = c("blue", "red"), lty = 1, lwd = 2)

```

```{r}
# calculate RMSE
rmse <- sqrt(mean((y_test - test_predictions)^2))
cat("RMSE: ", rmse, "\n")
```